// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB16LvNjiI8SJYbJD9XD46ratqjS1U6djs',
    appId: '1:50765823104:web:92d0be8fffe66b45957a65',
    messagingSenderId: '50765823104',
    projectId: 'cityfy-42eb0',
    authDomain: 'cityfy-42eb0.firebaseapp.com',
    storageBucket: 'cityfy-42eb0.firebasestorage.app',
    measurementId: 'G-LPXZ55HP7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRPNQGXopKfEe-KxbcN-HjA0wUMwnHY4',
    appId: '1:50765823104:android:08d545913c404b35957a65',
    messagingSenderId: '50765823104',
    projectId: 'cityfy-42eb0',
    storageBucket: 'cityfy-42eb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVwjUFk9gQ00odyeoJ5lCV_ZF82dCRbI',
    appId: '1:50765823104:ios:722a7e89a1623ea9957a65',
    messagingSenderId: '50765823104',
    projectId: 'cityfy-42eb0',
    storageBucket: 'cityfy-42eb0.firebasestorage.app',
    iosBundleId: 'com.example.cityguideApp',
  );
}
